Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  uploadDir: "uploads/"
  approot: "http://localhost:3000"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://paste.gnugen.ch"
  <<: *defaults
