Default: &defaults
  database: Paste.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Paste_test.sqlite3
  <<: *defaults

Staging:
  database: Paste_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Paste_production.sqlite3
  poolsize: 100
  <<: *defaults
